import { createContext } from 'react';

const GlobalContext = createContext({
  monthIdex: 0,
  setMonthIndex: () => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: () => {},
  daySelected: null,
  setDaySelected: () => {},
  showEventModal: false,
  setShowEventModal: () => {},
  showEditEvent: false,
  setShowEditEvent: () => {},
  showSearchEvent: false,
  setShowSearchEvent: () => {},
  bigCalendarSlcDay: null,
  setBigCalendarSlcDay: () => {},
  fromCreateBtn: null,
  setFromCreateBtn: () => {},
  eventStartDay: null,
  setEventStartDay: () => {},
  eventEndDay: null,
  setEventEndDay: () => {},
  events: null,
  setEvents: () => {},
  reNewEvents: true,
  setReNewEvents: () => {},
  user: null,
  setUser: () => {},
  currentDoc: null,
  setCurrentDoc: () => {},
  showUpdateModal: false,
  setShowUpdateModal: () => {},
});

export default GlobalContext;
